# Generated by Django 6.0.6 on 2026-06-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videk_szive', '0005_remove_guest_adult_number_remove_guest_arrive_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='not_cleaning',
            field=models.BooleanField(default=False, verbose_name='Nem kér takarítást'),
        ),
    ]
