# Generated by Django 6.0.6 on 2026-06-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videk_szive', '0006_room_not_cleaning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='not_cleaning',
            field=models.BooleanField(default=False, verbose_name='Takarítást nem kér'),
        ),
    ]
