# Generated by Django 6.0.5 on 2026-06-20 16:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videk_szive', '0007_alter_room_not_cleaning'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='issue_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RoomIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_issues', to='videk_szive.room')),
            ],
        ),
    ]
