# Generated by Django 6.0.5 on 2026-06-28 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videk_szive', '0009_cleaningtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomissue',
            name='handyman_note',
            field=models.TextField(blank=True, null=True, verbose_name='Karbantartó megjegyzése'),
        ),
    ]
