# Generated by Django 6.0.5 on 2026-06-28 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videk_szive', '0010_roomissue_handyman_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomissue',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Megoldás ideje'),
        ),
    ]
