# Generated by Django 6.0.5 on 2026-07-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videk_szive', '0011_roomissue_resolved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='wake_up_confirmed',
            field=models.BooleanField(default=False, verbose_name='Ébresztés visszaigazolva'),
        ),
        migrations.AddField(
            model_name='room',
            name='wake_up_time',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ébresztési időpont / Megjegyzés'),
        ),
    ]
