# Generated by Django 6.0.5 on 2026-07-25 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videk_szive', '0012_room_wake_up_confirmed_room_wake_up_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='videk_szive.room', verbose_name='Szoba'),
        ),
    ]
