# Generated by Django 6.0.5 on 2026-07-25 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videk_szive', '0013_alter_reservation_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='room_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
