# Generated by Django 6.0.5 on 2026-07-25 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videk_szive', '0014_reservation_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='room_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Szobatípus'),
        ),
    ]
