# Generated by Django 6.0.5 on 2026-07-25 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videk_szive', '0015_alter_reservation_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='videk_szive.room', verbose_name='Szoba'),
        ),
    ]
