# Generated by Django 6.0.5 on 2026-07-25 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videk_szive', '0016_alter_reservation_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Feldolgozásra vár'), ('CONFIRMED', 'Visszaigazolva / Check-inre vár'), ('CHECKED_IN', 'Bejelentkezett')], default='PENDING', max_length=20, verbose_name='Státusz'),
        ),
    ]
