# Generated by Django 6.0.6 on 2026-07-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videk_szive', '0017_reservation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Feldolgozásra vár'), ('CONFIRMED', 'Visszaigazolva / Check-inre vár'), ('CHECKED_IN', 'Bejelentkezett'), ('CHECKED_OUT', 'Kijelentkezett')], default='PENDING', max_length=20, verbose_name='Státusz'),
        ),
    ]
