# Generated by Django 6.0.6 on 2026-06-06 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=100, verbose_name='Vendég neve')),
                ('birth_date', models.DateField(verbose_name='Születési dátum')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefonszám')),
                ('personal_id', models.CharField(max_length=20, unique=True, verbose_name='Személyi igazolvány szám')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail cím')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lakcím')),
                ('arrive_date', models.DateField(verbose_name='Érkezés dátuma')),
                ('leave_date', models.DateField(verbose_name='Távozás dátuma')),
                ('adult_number', models.IntegerField(default=1, verbose_name='Felnőttek száma')),
                ('kid_number', models.IntegerField(default=0, verbose_name='Gyerekek száma')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Megjegyzés')),
            ],
            options={
                'verbose_name_plural': 'Guests',
            },
        ),
    ]
