# Generated by Django 6.0.6 on 2026-06-06 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videk_szive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_number', models.IntegerField(primary_key=True, serialize=False, verbose_name='Szobaszám')),
                ('room_type', models.CharField(max_length=50, verbose_name='Szobatípus')),
                ('room_persons', models.IntegerField(verbose_name='Férőhely')),
                ('room_size', models.IntegerField(verbose_name='Szobaméret (m²)')),
                ('balcony', models.BooleanField(default=False, verbose_name='Erkélyes')),
                ('status_free', models.BooleanField(default=True, verbose_name='Szabad')),
                ('price_per_night', models.IntegerField(verbose_name='Ár/éjszaka')),
                ('cleaning', models.BooleanField(default=False, verbose_name='Takarítást kér')),
                ('extra_sheets', models.BooleanField(default=False, verbose_name='Extra ágynemű')),
                ('extra_towel', models.BooleanField(default=False, verbose_name='Extra törölköző')),
                ('extra_showers', models.BooleanField(default=False, verbose_name='Extra tusfürdő')),
                ('bin_clean', models.BooleanField(default=False, verbose_name='Szemetes ürítés')),
                ('wake_up', models.BooleanField(default=False, verbose_name='Ébresztés kérése')),
                ('issues', models.BooleanField(default=False, verbose_name='Műszaki hiba')),
                ('wifi', models.CharField(blank=True, max_length=50, null=True, verbose_name='Wi-Fi jelszó')),
                ('current_guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='videk_szive.guest', verbose_name='Aktuális vendég')),
            ],
            options={
                'verbose_name_plural': 'Rooms',
            },
        ),
    ]
