# Generated by Django 6.0.6 on 2026-06-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videk_szive', '0002_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='statusBooked',
            field=models.BooleanField(default=False, verbose_name='Kiadott szoba'),
        ),
        migrations.AddField(
            model_name='room',
            name='statusCleaned',
            field=models.BooleanField(default=False, verbose_name='Kitakarított szoba'),
        ),
        migrations.AddField(
            model_name='room',
            name='statusNeedCleaning',
            field=models.BooleanField(default=False, verbose_name='Takarítandó szoba'),
        ),
        migrations.AddField(
            model_name='room',
            name='statusUnderCleaning',
            field=models.BooleanField(default=False, verbose_name='Takarítás alatt álló szoba'),
        ),
        migrations.AlterField(
            model_name='room',
            name='status_free',
            field=models.BooleanField(default=True, verbose_name='Szabad szoba'),
        ),
    ]
