# Generated by Django 6.0.6 on 2026-06-08 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videk_szive', '0003_room_statusbooked_room_statuscleaned_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='statusBooked',
            new_name='status_booked',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='statusCleaned',
            new_name='status_cleaned',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='statusNeedCleaning',
            new_name='status_need_cleaning',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='statusUnderCleaning',
            new_name='status_under_cleaning',
        ),
    ]
