# Generated by Django 6.0.5 on 2026-06-11 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videk_szive', '0004_rename_statusbooked_room_status_booked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='adult_number',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='arrive_date',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='kid_number',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='leave_date',
        ),
        migrations.RemoveField(
            model_name='room',
            name='status_booked',
        ),
        migrations.RemoveField(
            model_name='room',
            name='status_cleaned',
        ),
        migrations.RemoveField(
            model_name='room',
            name='status_need_cleaning',
        ),
        migrations.RemoveField(
            model_name='room',
            name='status_under_cleaning',
        ),
        migrations.AlterField(
            model_name='room',
            name='status_free',
            field=models.BooleanField(default=True, verbose_name='Szabad'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrive_date', models.DateField(verbose_name='Érkezés dátuma')),
                ('leave_date', models.DateField(verbose_name='Távozás dátuma')),
                ('adult_number', models.IntegerField(default=1, verbose_name='Felnőttek száma')),
                ('kid_number', models.IntegerField(default=0, verbose_name='Gyerekek száma')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Megjegyzés')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='videk_szive.guest', verbose_name='Vendég')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='videk_szive.room', verbose_name='Szoba')),
            ],
            options={
                'verbose_name_plural': 'Reservations',
            },
        ),
    ]
