# Generated by Django 6.0.5 on 2026-06-11 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videk_szive', '0006_room_not_cleaning'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='status_booked',
            field=models.BooleanField(default=False, verbose_name='Kiadott szoba'),
        ),
        migrations.AddField(
            model_name='room',
            name='status_cleaned',
            field=models.BooleanField(default=False, verbose_name='Kitakarított szoba'),
        ),
        migrations.AddField(
            model_name='room',
            name='status_need_cleaning',
            field=models.BooleanField(default=False, verbose_name='Takarítandó szoba'),
        ),
        migrations.AddField(
            model_name='room',
            name='status_under_cleaning',
            field=models.BooleanField(default=False, verbose_name='Takarítás alatt álló szoba'),
        ),
        migrations.AlterField(
            model_name='room',
            name='status_free',
            field=models.BooleanField(default=True, verbose_name='Szabad szoba'),
        ),
    ]
